# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - Detectify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          source venv/bin/activate
          export DJANGO_SETTINGS_MODULE=detectify_project.settings.production
          export SECRET_KEY=build-secret-key-for-static-collection
          export AZURE_POSTGRESQL_HOST=localhost
          export AZURE_POSTGRESQL_NAME=temp
          export AZURE_POSTGRESQL_USER=temp
          export AZURE_POSTGRESQL_PASSWORD=temp
          python manage.py collectstatic --noinput

      - name: Run tests (optional)
        run: |
          source venv/bin/activate
          # Add your test commands here if you have tests
          # python manage.py test

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "venv/*" "*.git*" "*__pycache__*" "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_YOUR_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_YOUR_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_YOUR_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'your-app-name-here'
          slot-name: 'Production'
          package: .
          startup-command: 'bash startup.sh'