# Generated by Django 4.2.7 on 2025-08-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("frame_number", models.IntegerField()),
                ("person_count", models.IntegerField()),
                ("bounding_boxes", models.JSONField()),
                ("confidence_scores", models.JSONField()),
                ("person_ids", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_detections",
                        to="cases.videoupload",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["video", "timestamp"],
                        name="cases_peopl_video_i_829f1f_idx",
                    ),
                    models.Index(
                        fields=["person_count"], name="cases_peopl_person__2f3e4f_idx"
                    ),
                ],
            },
        ),
    ]
