# Generated by Django 4.2.7 on 2025-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_peopledetection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedvideo",
            name="processed_file",
        ),
        migrations.RemoveField(
            model_name="suspectimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="videoupload",
            name="video_file",
        ),
        migrations.AddField(
            model_name="processedvideo",
            name="processed_data",
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processedvideo",
            name="processed_name",
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processedvideo",
            name="processed_size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processedvideo",
            name="processed_type",
            field=models.CharField(default="mp4", max_length=10),
        ),
        migrations.AddField(
            model_name="suspectimage",
            name="image_data",
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspectimage",
            name="image_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspectimage",
            name="image_size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspectimage",
            name="image_type",
            field=models.CharField(
                choices=[("jpg", "JPEG"), ("png", "PNG"), ("jpeg", "JPEG")],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videoupload",
            name="video_data",
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videoupload",
            name="video_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videoupload",
            name="video_size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videoupload",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("mp4", "MP4"),
                    ("avi", "AVI"),
                    ("mkv", "MKV"),
                    ("mov", "MOV"),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
